CREATE TABLE IF NOT EXISTS MEETING_ROOM (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MEETING_ROOM_BOOKING (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    meeting_room_id BIGINT NOT NULL,
    employee_email VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time_from TIME NOT NULL,
    time_to TIME NOT NULL,
    CONSTRAINT fk_meeting_room FOREIGN KEY (meeting_room_id) REFERENCES MEETING_ROOM(id)
);
